### ISSUE TITLE
istallazione mapurl 

### ISSUE THREAD

**Issue by stetin67** [tanto/geopapurls#3]
mi scusi, ma sono nuovo su android, abbiamo preso uno zenpad perché vorremmo utilizzare i servizi wms della regione toscana in campagna. Abbiamo istallato geopaparazzi3 ma non riusciamo a far funzionare il servizio di scaricamento mapurl TANTO.
Ho scaricato il file tanto-geopapurls-9ba27e0.zip che presumo contenga il servizio ma non riesco a istallarlo sul dispositivo.
Potrebbe darmi qualche indicazione?
saluti e buona Pasqua.

stefano tintori

**Comment by moovida** [comment]
@giohappy , riesci a capire cosa potrebbe essere successo?

@stetin67 , in teoria tutto dovrebbe essere trasparente all'utente e non dovrebbe scaricare uno zip, bensi' un file .mapurl installato da geopaparazzi. 

Intanto segno questa issue come un baco e vediamo cosa succede :-)

**Comment by stetin67** [comment]
ora sembrerebbe funzionare anche se non correttamente: se lascio baffato "usa coordinate..."  e "limita i risultati a 20" mi restituisce anche layer americani (il gps mi da la posizione corretta sulla mappa"; se filtro su toscana mi restituisce solo i layer relativi alle ortofotocarte e non gli altri servizi wms disponibili (es a noi servirebbero catasto e CTR, non so se sono inseriti nel servizio scaricamento)

**Comment by moovida** [comment]
Riguardo ai layer americani: se la loro estensione fornita si espande su tutto il globo, li si troverebbe comunque anche filtrando sulla coordinata.

Per quanto riguarda il catasto e CTR, non ho idea se sono inseriti. E' possibile comunque aprire una issue di richiesta qui nel caso in cui mancassero.

**Comment by giohappy** [comment]
Ciao,
il problema dei layer americani, come già detto da Andrea, è che se il WMS fornisce un'estensione globale (anche se i dati sono solo localizzati negli USA) mapurls li restituirà comunque. Effettivamente vedo che molti servizi (non solo americani) dichiarano un'estensione ben più ampio di quella effettiva.

CTR e catasto toscana non sono presenti (i layer disponibili li puoi vedere [qua](http://mapurls.geopaparazzi.eu/layers/)), ma puoi [inserire un suggerimento](http://mapurls.geopaparazzi.eu/suggest) magari facendo riferimento a quelli del servizio Geoscopio di Regione Toscana.

**Comment by giohappy** [comment]
Inseriti i servizi richiesti
