### ISSUE TITLE
Non riesco a scaricare i link wms

### ISSUE THREAD

**Issue by Ciccio3** [tanto/geopapurls#5]
Andando in Import, mapurls, e impostando la ricerca dei link wms, riesco a vedere l'elenco di quelli disponibili (per esempio le ctr dell'Emilia-Romagna) ma a fianco non c'è l'icona per scaricare il collegamento:
![screenshot_2017-12-15-00-08-16](https://user-images.githubusercontent.com/34556920/34018852-351abe8c-e12c-11e7-9385-0a80947f5921.png)
Sto sbagliando qualcosa? Devo installare qualche altro programma?
Sto usando l'ultima versione di geopaparazzi 5.5.5 su telefono LG G6.

**Comment by moovida** [comment]
Mi sa tanto che questo e' un problema del nuovo set di icone di geopaparazzi. Ci guardo.

**Comment by moovida** [comment]
Risolto in geopaparazzi. Disponibile con la prossima release.
